name: Release Library

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Get Version from package.json
        run: |
          PACKAGE_VERSION=$(jq -r .version package.json)
          echo "export APP_VERSION=$PACKAGE_VERSION" >> $GITHUB_ENV

      - name: Check Existing Release
        run: |
          existing_tag=$(gh release view ${{ env.APP_VERSION }} --json tag_name -q '.tag_name' || echo "")
          if [[ -z "$existing_tag" ]]; then
            echo "Release ${{ env.APP_VERSION }} doesn't exist. Creating a new release..."
          else
            echo "Release ${{ env.APP_VERSION }} already exists. Skipping the release creation."
            exit 0
          fi
        if: steps.version-check.outputs.APP_VERSION
    

      - name: Create Git Tag
        run: |
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git config user.name "${{ github.actor }}"
          git tag -a v${{ env.APP_VERSION }} -m "Version ${{ env.APP_VERSION }}"

      - name: Save Commit Messages as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: commit-messages
          path: commit_messages.txt

      - name: Create Release with GitHub CLI
        run: |
          PACKAGE_VERSION=$(jq -r .version package.json)
          echo "export APP_VERSION=$PACKAGE_VERSION" >> $GITHUB_ENV
          # Create a new branch (e.g., release)
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git config user.name "${{ github.actor }}"
          version=$PACKAGE_VERSION  # Use the correct variable name

          release_title="v$version"

          tag="v$version"

          git log -n 1  --pretty=format:"- %s (%an)" > commit_messages.txt

          # Create a GitHub release with release notes using gh
          gh release create $tag  --title "$release_title" --notes-file commit_messages.txt

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      